version: '3.8'

services:
  tkdai-app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres.imvteekyazlzrtvooknh:Sc123034!@aws-0-us-east-1.pooler.supabase.com:6543/postgres
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  tkdai-data: 